// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlurpJob.Data;

#nullable disable

namespace SlurpJob.Migrations
{
    [DbContext(typeof(SlurpContext))]
    [Migration("20260201231303_AddClassifierId")]
    partial class AddClassifierId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SlurpJob.Models.EvidenceLocker", b =>
                {
                    b.Property<long>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PayloadBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("IncidentId");

                    b.ToTable("EvidenceLocker");
                });

            modelBuilder.Entity("SlurpJob.Models.IncidentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassifierId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassifierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("IncidentLog");
                });

            modelBuilder.Entity("SlurpJob.Models.EvidenceLocker", b =>
                {
                    b.HasOne("SlurpJob.Models.IncidentLog", "Incident")
                        .WithOne("Evidence")
                        .HasForeignKey("SlurpJob.Models.EvidenceLocker", "IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("SlurpJob.Models.IncidentLog", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
